import { useState } from 'react';
import { withRouter } from 'next/router';
import {
  Breadcrumb,
  InputNumber,
  Pagination,
  Tabs
} from 'antd';
import Header from '@/components/Header';
import GoodsItem from '@/components/GoodsItem';
import Navgation from '@/components/Navgation';
import styles from './index.module.less';

const Goods = (props) => {
  let {
    name
  } = props?.router?.query;
  const { TabPane } = Tabs;
  const onHandleChange = (key) => {
    console.log(key);
  };
  const onChange = (currentSlide) => {
    // console.log(currentSlide);
  };
  const showTotal = (total) => `Total ${total} items`;
  const handleChange = (value) => {
    // console.log('value', value)
  }
  return (
    <div className={styles.goods_view}>
      <Header
        title='Create Next App Test'
        content='Generated by create next app'
        description='Generated by create next app'
      />
      <main className={styles.goods_view_container}>
        <div>
          <Navgation />
        </div>
        <div className={styles.goods_view_category}>
          <div className={styles.goods_view_category_breadcrumb}>
            <Breadcrumb>
              <Breadcrumb.Item>全部</Breadcrumb.Item>
              <Breadcrumb.Item>生活电器</Breadcrumb.Item>
              <Breadcrumb.Item>电视</Breadcrumb.Item>
            </Breadcrumb>
          </div>
        </div>
        <div className={styles.goods_view_info}>
          <div className={styles.goods_view_info_imgs}>
            <img
              src='/static/images/goods/img1.png'
              className={styles.goods_view_info_imgs_big}
            />
            <div className={styles.goods_view_info_imgs_smallList}>
              {
                [2,3,4,5].map(item=>
                  <img
                    src={`/static/images/goods/img${item}.png`}
                    className={styles.goods_view_info_imgs_smallList_item}
                  />
                )
              }
            </div>
          </div>
          <div className={styles.goods_view_info_detail}>
            <h3 className={styles.goods_view_info_detail_name}>
              戴尔（DELL） INS 24-5490-R1528W 23.8“一体机电脑 i5-10210U|8G|1T HDD|win 10|3年质保|2G 独显
            </h3>
            <div className={styles.goods_view_info_detail_price}>
              <div className={styles.goods_view_info_detail_price_number}>
                价格<span>¥6999.00</span>
              </div>
              <div className={styles.goods_view_info_detail_price_sales}>
                <p className={styles.goods_view_info_detail_price_sales_num}>88</p>
                <p className={styles.goods_view_info_detail_price_sales_text}>月销量</p>
              </div>
            </div>
            <div className={styles.goods_view_info_detail_skus}>
              <div className={styles.goods_view_info_detail_skus_control}>
                <label className={styles.goods_view_info_detail_skus_control_label}>规格</label>
                <div className={styles.goods_view_info_detail_skus_control_list}>
                  <div className={styles.goods_view_info_detail_skus_control_list_item}>规格一</div>
                  <div className={styles.goods_view_info_detail_skus_control_list_item}>规格二</div>
                  <div className={styles.goods_view_info_detail_skus_control_list_item}>规格三</div>
                  <div className={styles.goods_view_info_detail_skus_control_list_item}>规格四</div>
                </div>
              </div>
              <div className={styles.goods_view_info_detail_skus_control}>
                <label className={styles.goods_view_info_detail_skus_control_label}>颜色</label>
                <div className={styles.goods_view_info_detail_skus_control_list}>
                  <div className={styles.goods_view_info_detail_skus_control_list_item}>金色</div>
                  <div className={styles.goods_view_info_detail_skus_control_list_item}>银色</div>
                  <div className={styles.goods_view_info_detail_skus_control_list_item}>玫红</div>
                  <div className={styles.goods_view_info_detail_skus_control_list_item}>彩色</div>
                </div>
              </div>
            </div>
            <div className={styles.goods_view_info_detail_num}>
              <label className={styles.goods_view_info_detail_num_label}>数量</label>
              <div className={styles.goods_view_info_detail_num_info}>
                <div className={styles.goods_view_info_detail_num_info_operates}>
                  <div className={styles.goods_view_info_detail_num_info_operates_min}>-</div>
                  <InputNumber
                    onChange={handleChange}
                    value={1}
                  />
                  <div className={styles.goods_view_info_detail_num_info_operates_add}>+</div>
                </div>
                库存 100 件
              </div>
            </div>
            <div className={styles.goods_view_info_detail_operates}>
              <div className={`${styles.goods_view_info_detail_operates_item} ${styles.collect}`}>
                <img
                  src='/static/images/goods/add_black.png'
                  className={styles.goods_view_info_detail_operates_item_icon}
                />
                收藏
              </div>
              <div className={`${styles.goods_view_info_detail_operates_item} ${styles.addcart}`}>
                <img
                  src='/static/images/goods/add_white.png'
                  className={styles.goods_view_info_detail_operates_item_icon}
                />
                加入购物车
              </div>
            </div>
          </div>
        </div>
        <div className={styles.goods_view_note}>
          <label className={styles.goods_view_note_label}>售前须知：</label>
          <p className={styles.goods_view_note_value}>由于客户的原因，导致在包裹中含有禁运物品，从而引起的包裹退运以及相关的费用及责任，均由客户承担。所有在我司提交的订单，均默认为您已经阅读过、明确理解并且同意严格遵守上述规定！</p>
        </div>
        <div className={styles.goods_view_detail}>
          <div className={styles.goods_view_detail_desc}>
            <Tabs defaultActiveKey="1" onChange={onChange}>
              <TabPane tab="商品详情" key="1">
                <div className={styles.goods_view_detail_desc_goodsDesc}>
                  <img
                    src='https://img30.360buyimg.com/sku/jfs/t1/34108/35/10763/386014/5ccfe99bEbf33e32f/cb643687598d9bd4.jpg.avif'
                    className={styles.goods_view_detail_desc_goodsDesc_item}
                  />
                  <img
                    src='https://img30.360buyimg.com/sku/jfs/t1/37151/34/6742/132401/5cc51b1cE4cdbfd48/0b678e0532d94039.jpg.avif'
                    className={styles.goods_view_detail_desc_goodsDesc_item}
                  />
                </div>
              </TabPane>
              <TabPane tab="商品评价" key="2">
                <div className={styles.goods_view_detail_evaluate}>
                  <div className={styles.goods_view_detail_evaluate_list}>
                    {
                      [1,2,3,4,5,6,7].map(item=>
                        <div
                          key={item}
                          className={styles.goods_view_detail_evaluate_list_item}
                        >
                          <p className={styles.goods_view_detail_evaluate_list_item_value}>
                          老板发货及时，物流也很快。好评！老板发货及时，物流也很快。好评！老板发货及时，物流也很快。好评！老板发货及时，物流也很快。好评！
                          </p>
                          <p className={styles.goods_view_detail_evaluate_list_item_desc}>
                            <span>2022.09.12</span>
                            <span>颜色分类：金色</span>
                          </p>
                          <p className={styles.goods_view_detail_evaluate_list_item_user}>有***爱</p>
                        </div>
                      )
                    }
                  </div>
                  <div className={styles.goods_view_detail_evaluate_pagination}>
                    <Pagination
                      size="small"
                      total={50}
                      disabled
                      showTotal={showTotal}
                      showSizeChanger
                      showQuickJumper
                    />
                  </div>
                </div>
              </TabPane>
            </Tabs>
          </div>
          <div className={styles.goods_view_detail_other}>
            <div className={styles.goods_view_detail_other_shop}>
              <div className={styles.goods_view_detail_other_shop_info}>
                <div className={styles.goods_view_detail_other_shop_info_name}>
                  浙江仲基贸易有限公司
                  <span className={styles.goods_view_detail_other_shop_info_name_tag}>5年老店</span>
                </div>
                <div className={styles.goods_view_detail_other_shop_info_location}>地址：浙江省杭州市滨江国贸大厦23号</div>
              </div>
              <div className={styles.goods_view_detail_other_shop_rate}>
                <div className={styles.goods_view_detail_other_shop_rate_item}>
                  店铺评分
                  <div className={styles.goods_view_detail_other_shop_rate_item_more}>
                    <span className={styles.goods_view_detail_other_shop_rate_item_more_score}>4.9</span>
                    分
                    <img
                      src='/static/images/up.png'
                      className={styles.goods_view_detail_other_shop_rate_item_more_icon}
                    />
                  </div>
                </div>
                <div className={styles.goods_view_detail_other_shop_rate_item}>
                  物流速度
                  <div className={styles.goods_view_detail_other_shop_rate_item_more}>
                    <span className={styles.goods_view_detail_other_shop_rate_item_more_score}>4.9</span>
                    分
                    <img
                      src='/static/images/up.png'
                      className={styles.goods_view_detail_other_shop_rate_item_more_icon}
                    />
                  </div>
                </div>
                <div className={styles.goods_view_detail_other_shop_rate_item}>
                  店铺评价
                  <div className={styles.goods_view_detail_other_shop_rate_item_more}>
                    <span className={styles.goods_view_detail_other_shop_rate_item_more_score}>4.9</span>
                    分
                    <img
                      src='/static/images/up.png'
                      className={styles.goods_view_detail_other_shop_rate_item_more_icon}
                    />
                  </div>
                </div>
                <div className={styles.goods_view_detail_other_shop_rate_item}>
                  服务态度
                  <div className={styles.goods_view_detail_other_shop_rate_item_more}>
                    <span className={styles.goods_view_detail_other_shop_rate_item_more_score}>4.9</span>
                    分
                    <img
                      src='/static/images/up.png'
                      className={styles.goods_view_detail_other_shop_rate_item_more_icon}
                    />
                  </div>
                </div>
              </div>
            </div>
            <div className={styles.goods_view_detail_other_recommond}>
              <h3 className={styles.goods_view_detail_other_recommond_title}>热销推荐</h3>
              <div className={styles.goods_view_detail_other_recommond_list}>
                {
                  [1,2,3].map(item=>
                    <div
                      key={item}
                      className={styles.goods_view_detail_other_recommond_list_item}
                    >
                      <GoodsItem
                        img='https://img10.360buyimg.com/ceco/s150x150_jfs/t1/140639/38/15125/38170/5fb63195Ea2a563f1/18ed7df2cc89e759.jpg!q70.jpg.avif'
                        goodsName='苹果 背光键盘 轻薄笔记本'
                        price='9999.00'
                      />
                    </div>
                  )
                }
              </div>
            </div>
          </div>
        </div>
        
      </main>
    </div>
  )
}
export default withRouter(Goods);