import { useState } from 'react';
import Router from 'next/router';
import Header from '@/components/Header';
import {
  Button,
  Checkbox,
  Input
} from 'antd';
import styles from './index.module.less';

const Login = (props) => {
  const onChange = (e) => {
    // console.log(`checked = ${e.target.checked}`);
  };
  const forgetPwd = () => {
    Router.push('/findpwd')
  }
  const resgier = () => {
    Router.push('/register')
  }
  return (
    <div>
      <Header
        title='Create Next App Test'
        content='Generated by create next app'
        description='Generated by create next app'
      />
      <main className={styles.login_view}>
        <div className={styles.login_view_main}>
          <div className={styles.login_view_main_section}>
            <div className={styles.login_view_main_section_content}>
              <h3 className={styles.login_view_main_section_content_title}>密码登录</h3>
              <Input
                placeholder="请输入账号"
                allowClear={true}
                className={styles.login_view_main_section_content_control}
              />
              <Input
                placeholder="请输入登录密码"
                allowClear={true}
                type='password'
                className={styles.login_view_main_section_content_control}
              />
              <Button className={styles.login_view_main_section_content_submit}>登录</Button>
              <div className={styles.login_view_main_section_content_actions}>
                <Checkbox
                  onChange={onChange}
                >
                  记住密码
                </Checkbox>
                <div className={styles.login_view_main_section_content_actions_item}>
                  <p
                    className={styles.login_view_main_section_content_actions_item_single}
                    onClick={()=>{forgetPwd()}}
                  >
                    忘记密码
                  </p>
                  <p
                    className={styles.login_view_main_section_content_actions_item_single}
                    onClick={()=>{resgier()}}
                  >
                    注册
                  </p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
export default Login;