import { useState } from 'react';
import Router from 'next/router';
import Header from '@/components/Header';
import {
  Button,
  Checkbox,
  Input
} from 'antd';
import styles from './index.module.less';

const Login = (props) => {
  const onChange = (e) => {
    // console.log(`checked = ${e.target.checked}`);
  };
  const login = () => {
    Router.push('/login')
  }
  return (
    <div>
      <Header
        title='Create Next App Test'
        content='Generated by create next app'
        description='Generated by create next app'
      />
      <main className={styles.findpwd_view}>
        <div className={styles.findpwd_view_main}>
          <div className={styles.findpwd_view_main_section}>
            <div className={styles.findpwd_view_main_section_content}>
              <h3 className={styles.findpwd_view_main_section_content_title}>
                密码找回
                <span
                  className={styles.findpwd_view_main_section_content_title_login}
                  onClick={()=>{login()}}
                >
                  直接登录
                </span>
              </h3>
              <div className={styles.findpwd_view_main_section_content_controls}>
                <Input
                  placeholder="请输入账号"
                  allowClear={true}
                  className={styles.findpwd_view_main_section_content_control}
                />
                <div className={styles.findpwd_view_main_section_content_controls_getcode}>获取验证码</div>
              </div>
              <Input
                placeholder="请输入验证码"
                allowClear={true}
                type='text'
                className={styles.findpwd_view_main_section_content_control}
              />
              <Input
                placeholder="请输入登录密码"
                allowClear={true}
                type='password'
                className={styles.findpwd_view_main_section_content_control}
              />
              <Button className={styles.findpwd_view_main_section_content_submit}>登录</Button>
            </div>
          </div>
        </div>
      </main>
    </div>
  )
}
export default Login;